### ISSUE TITLE
Ban Room Spams

### ISSUE THREAD

**Issue by Webx123** [Tinychat/Tinychat-Bot#6]
On your tc bot how would i add where it autobans tinychat urls? ppl keep spamming my room i want any tinychat.com/blablah auto banned

**Comment by Ruddernation-Designs** [comment]
Hi @Webx123 
I've currently stopped updating the TC bot, 
But if I get time this week I will add it so URL's can be banned too,
I may just add it to banned strings or do a new function so it'll ban any tinychat URL being posted.

**Comment by Ruddernation-Designs** [comment]
Hi @Webx123 
Please update the tinybot.py file and use command `badword url`
You do not need to add the http:// or https:// as it will ban the url even if you add without them.

**Comment by Webx123** [comment]
ohh so tinychat.com would add tinychat.com/anyroomname

**Comment by Ruddernation-Designs** [comment]
Hi @Webx123 
I never tested on just tinychat.com but give it a try and let me know if it works,
But added the specific room works, 
example:
badword tinychat.com/anyroom
badword tinychat.com/anotherroom
the way it's set now is it doesn't matter where the URL is posted in a sentence it will still be banned, The same goes for any words you have added to the file too.

**Comment by Webx123** [comment]
wouldnt adding tinychat.com as a badword do it then? anytime tinychat.com is posted it bans

**Comment by Ruddernation-Designs** [comment]
I never tested it, Just give it a try and see if it works

**Comment by kiratsuchi** [comment]
Hello. Thanks alot for the bot man. It works very well and its helpful. Just quick 2 things I'am curious about: 1) I have no issue running this on windows 10 with python 2.7; however, on ubuntu 16.04 i installed the pip modules with python2.7 instead of python3 and for some reason bot always says its missing handlers and runs error. 2) Lastly, I know regular users cannot issue mod commands (thank god); however the room I moderator I don't own. Is there a way I could give a specific account mod control so it can execute mod commands without having a star?
